export const concepts = Object.freeze([
  Object.freeze({
    number: "01",
    slug: "01-ringside-signal",
    title: "Held Seat",
    descriptor: "Quiet invitation · space kept open",
    image: "wrapped-corner.webp",
    alt: "A worn off-white wrap turns a stitched corner over layered blue canvas.",
  }),
  Object.freeze({
    number: "02",
    slug: "02-between-rounds",
    title: "Side by Side",
    descriptor: "Shared ground · no forced eye contact",
    image: "between-rounds-material.webp",
    alt: "Folded off-white wrap and torn paper rest on worn blue canvas beside a small yellow mark.",
  }),
  Object.freeze({
    number: "03",
    slug: "03-open-corner",
    title: "The Check-In",
    descriptor: "Direct question · human answer",
    image: "open-corner-material.webp",
    alt: "Layered blue cloth frames an open off-white corner joined by a short yellow stitch.",
  }),
  Object.freeze({
    number: "04",
    slug: "04-first-bell",
    title: "At the Corner",
    descriptor: "Between rounds · steady support",
    image: "first-bell-signal.webp",
    alt: "Concentric rings pressed into blue canvas are interrupted by a single yellow mark.",
  }),
  Object.freeze({
    number: "05",
    slug: "05-someone-in-your-corner",
    title: "The Long Walk",
    descriptor: "Forward motion · room to talk",
    image: "held-space.webp",
    alt: "A worn blue padded corner is held together by a small yellow stitch.",
  }),
  Object.freeze({
    number: "06",
    slug: "06-kitchen-light",
    title: "Kitchen Light",
    descriptor: "After hours · honest conversation",
    image: "kitchen-light-collage.webp",
    alt: "Blue cloth panels and off-white paper strips cross in warm window light with a small yellow accent.",
  }),
  Object.freeze({
    number: "07",
    slug: "07-workday-pause",
    title: "Workday Pause",
    descriptor: "Pressure breaks · breath returns",
    image: "workday-pause.webp",
    alt: "Folded off-white cloth rests over a marked blue card on a bright blue surface.",
  }),
  Object.freeze({
    number: "08",
    slug: "08-what-hands-say",
    title: "What Hands Say",
    descriptor: "Small gestures · visible care",
    image: "canvas-print.webp",
    alt: "Three rope impressions run across deep blue canvas beside off-white paint and a yellow dot.",
  }),
  Object.freeze({
    number: "09",
    slug: "09-listening-room",
    title: "Listening Room",
    descriptor: "Clinical trust · human warmth",
    image: "cyanotype.webp",
    alt: "A cyanotype of coiled rope and fabric lies across handmade off-white paper.",
  }),
  Object.freeze({
    number: "10",
    slug: "10-blue-margin",
    title: "Blue Margin",
    descriptor: "Editorial clarity · measured truth",
    image: "paper-collage.webp",
    alt: "Torn off-white and blue paper layers overlap with rope shadows and a thin yellow mark.",
  }),
  Object.freeze({
    number: "11",
    slug: "11-on-the-other-end",
    title: "On the Other End",
    descriptor: "Reach out · someone answers",
    image: "other-end-cord.webp",
    alt: "White cord lines meet at a small yellow knot over stitched blue canvas.",
  }),
  Object.freeze({
    number: "12",
    slug: "12-two-ways-in",
    title: "Two Ways In",
    descriptor: "Members and therapists · one corner",
    image: "two-ways-in.webp",
    alt: "Layered blue fabric and torn off-white paper form two paths around a small yellow square.",
  }),
]);
