export const referenceHero = Object.freeze({
  image: "blue-corner-reference-ring.webp",
  width: 1774,
  height: 887,
  alt: "An empty black boxing-ring corner with white ropes and a single wooden stool.",
});

export const concepts = Object.freeze([
  Object.freeze({
    ordinal: "01",
    slug: "04-first-bell",
    title: "Reference master",
    descriptor: "Exact supplied base · no add-on",
    additionKey: null,
  }),
  Object.freeze({
    ordinal: "02",
    slug: "03-open-corner",
    title: "No perfect words needed",
    descriptor: "Three practical ways to begin",
    additionKey: "openingLines",
  }),
  Object.freeze({
    ordinal: "03",
    slug: "06-kitchen-light",
    title: "The first ten minutes",
    descriptor: "A plain-language first-session map",
    additionKey: "firstTenMinutes",
  }),
  Object.freeze({
    ordinal: "04",
    slug: "09-listening-room",
    title: "The Corner Standard",
    descriptor: "Visible therapist trust criteria",
    additionKey: "cornerStandard",
  }),
  Object.freeze({
    ordinal: "05",
    slug: "11-on-the-other-end",
    title: "Between-round plan",
    descriptor: "A private take-home next-step outline",
    additionKey: "betweenRoundPlan",
  }),
  Object.freeze({
    ordinal: "06",
    slug: "12-two-ways-in",
    title: "Bring someone into your corner",
    descriptor: "An optional, consent-led support path",
    additionKey: "trustedPerson",
  }),
  Object.freeze({
    ordinal: "07",
    slug: "01-ringside-signal",
    title: "Private readiness check",
    descriptor: "A private reflection with no score or diagnosis",
    additionKey: "readinessCheck",
  }),
  Object.freeze({
    ordinal: "08",
    slug: "02-between-rounds",
    title: "Between-round reset",
    descriptor: "A short grounding card for the next minute",
    additionKey: "resetCard",
  }),
  Object.freeze({
    ordinal: "09",
    slug: "05-someone-in-your-corner",
    title: "Ask for support",
    descriptor: "A plain-language support-request builder",
    additionKey: "supportRequest",
  }),
  Object.freeze({
    ordinal: "10",
    slug: "07-workday-pause",
    title: "Workday boundary",
    descriptor: "A workplace boundary script you control",
    additionKey: "workdayBoundary",
  }),
  Object.freeze({
    ordinal: "11",
    slug: "08-what-hands-say",
    title: "Body-signal check-in",
    descriptor: "Notice a body signal without diagnosing it",
    additionKey: "bodySignal",
  }),
  Object.freeze({
    ordinal: "12",
    slug: "10-blue-margin",
    title: "Questions before booking",
    descriptor: "A private checklist for a first fit conversation",
    additionKey: "bookingQuestions",
  }),
]);
