export const concepts = Object.freeze([
  Object.freeze({
    number: "03",
    slug: "03-open-corner",
    title: "The Check-In",
    descriptor: "Direct question · human answer",
    image: "open-corner-material.webp",
    alt: "Layered blue cloth frames an open off-white corner joined by a short yellow stitch.",
  }),
  Object.freeze({
    number: "04",
    slug: "04-first-bell",
    title: "At the Corner",
    descriptor: "Between rounds · steady support",
    image: "blue-corner-stool-hero.webp",
    imageWidth: 1774,
    imageHeight: 887,
    alt: "A worn wooden stool with blue hand wraps sits beside an empty boxing ring lit by warm window light.",
  }),
  Object.freeze({
    number: "06",
    slug: "06-kitchen-light",
    title: "Kitchen Light",
    descriptor: "After hours · honest conversation",
    image: "kitchen-light-collage.webp",
    alt: "Blue cloth panels and off-white paper strips cross in warm window light with a small yellow accent.",
  }),
  Object.freeze({
    number: "09",
    slug: "09-listening-room",
    title: "Listening Room",
    descriptor: "Clinical trust · human warmth",
    image: "cyanotype.webp",
    alt: "A cyanotype of coiled rope and fabric lies across handmade off-white paper.",
  }),
  Object.freeze({
    number: "11",
    slug: "11-on-the-other-end",
    title: "On the Other End",
    descriptor: "Reach out · someone answers",
    image: "other-end-cord.webp",
    alt: "White cord lines meet at a small yellow knot over stitched blue canvas.",
  }),
  Object.freeze({
    number: "12",
    slug: "12-two-ways-in",
    title: "Two Ways In",
    descriptor: "Members and therapists · one corner",
    image: "two-ways-in.webp",
    alt: "Layered blue fabric and torn off-white paper form two paths around a small yellow square.",
  }),
]);
